name: finaltest
description: A simple banking app built with Flutter.
publish_to: 'none'

# ✅ SDK version constraint
environment:
  sdk: ">=3.7.0 <4.0.0"

# ✅ Flutter dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

# ✅ Flutter configuration
flutter:
  uses-material-design: true
